### ISSUE TITLE
bad complexity of Array functions

### ISSUE THREAD

**Issue by kuribas** [purescript/purescript-arrays#13] opened 2014-08-17 17:23 UTC
Because Array.slice has complexity 0(n), many of the functions in Data.Array have a worse complexity than they should have.
head is O(n) instead of O(1)
last is O(n^2) where it could be O(1)
tail is O(n) (due to copying instead of sharing)

I find that pattern matching on Arrays using cons syntax is generally a bad idea.  It almost always leads to worse performance than expected.  Functional programmers are used to pattern matching being free (O(1)).  By having
cons patterns which are O(n), it may confuse programmers and give unexpected performance penalties.
The examples shown on the patterns documentation (sum and addPairs) are also O(n^2).

**Comment by jacereda** [comment] 2015-02-09 21:54
@kuribas do you mean tail can be implemented better than O(n)? How?

**Comment by kuribas** [comment] 2015-02-09 22:28
@jacereda if you change the representation from an Array as an range and a JS array, like how vectors are shared in the vector package in haskell, but paf31 said that would break the FFI, so basicly no.

**Comment by paf31** [comment] 2015-02-10 00:52
It wouldn't break the FFI, but it is a different type, so it needs a different foreign type. It would make a nice library though.

**Comment by jacereda** [comment] 2015-02-12 11:01
Something like this?

https://github.com/jacereda/purescript-slices

**Comment by paf31** [comment] 2015-02-12 17:28
I like it :)

**Comment by hdgarrood** [comment] 2015-03-03 06:00
I just posted on the mailing list about this issue - it might be of interest. https://groups.google.com/forum/#!topic/purescript/uF-SqphMeEg

TLDR - should we be encouraging use of native arrays at all (except for interop), when we can use other data structures which are better suited to functional programs, like Haskell's Data.Sequence?

**Comment by hdgarrood** [comment] 2015-03-18 18:14
Now that #28 has been merged, and given that deprecating cons syntax is planned on an issue in the purescript repo (purescript/purescript#937), I think this should be closed; I don't think there's anything else that can be done in this library to mitigate this issue.

**Comment by paf31** [comment] 2015-03-18 18:17
Agreed. We have better data structures for different classes of problems. The issue is just getting people to use them, I suppose.

**Comment by alexchandel** [comment] 2015-03-18 20:21
It's too bad the purescript optimizer can't combine/optimize the array functions & pattern matching. Isn't `head` just `[0]` in JS?

**Comment by paf31** [comment] 2015-03-18 20:24
Well, when I finally implement rewrite rules, maybe that will be possible.

**Comment by alexchandel** [comment] 2015-03-18 20:44
@paf31 wait, that doesn't happen automatically? I guess I assumed that everything except `Eff`s could be subject to rewriting, inlining, or outright deletion by the optimizer.

**Comment by paf31** [comment] 2015-03-18 20:46
There are a handful of baked-in optimizations, it's not a general-purpose optimizer.

**Comment by garyb** [comment] 2015-06-19 14:20
Closing this as it's semi-addressed now. Cons patterns for arrays have been removed in the compiler and some work has been done to optimise various array functions.

**Closed by garyb** 2015-06-19 14:20 UTC
Labels: enhancement
